# Generated by Django 4.0.4 on 2022-04-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='qualification',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_permis',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
