# Generated by Django 4.0.3 on 2022-05-04 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flotte', '0002_alter_affectation_chauffeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='chauffeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chauffeur_affectation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='date_debut',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='date_fin',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='etat',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicule_affectation', to='flotte.vehicule'),
        ),
        migrations.AlterField(
            model_name='consommation',
            name='consommation',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='consommation',
            name='consommation_totale',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='consommation',
            name='kilometrage',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='consommation',
            name='mois',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='consommation',
            name='type',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='consommation',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicule_consommation', to='flotte.vehicule'),
        ),
        migrations.AlterField(
            model_name='contratachat',
            name='chassis',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='contratachat',
            name='marque',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='contratachat',
            name='modele',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='contratachat',
            name='moteur',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='contratachat',
            name='prix',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='contratachat',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicule_contrat_achat', to='flotte.vehicule'),
        ),
        migrations.AlterField(
            model_name='contratachat',
            name='vendeur',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='contratlocation',
            name='date_debut',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='contratlocation',
            name='date_fin',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='contratlocation',
            name='marque',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='contratlocation',
            name='modele',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='contratlocation',
            name='prix',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='contratlocation',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicule_contrat_location', to='flotte.vehicule'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='activite',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='carrosserie',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='charge_utile',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='consommation',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='constructeur',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='cylidree',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='date_pmc',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='energie',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='engin',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='entretien',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='genre',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='kilometrage',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='nombre_debout',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='nombre_essieux',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='nombre_places',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='num_serie',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='poids_vide',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='ptac_ptra',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='puissance_fiscale',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='type_commercial',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='type_constructeur',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
