# Generated by Django 4.0.3 on 2022-05-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flotte', '0003_alter_affectation_chauffeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='etat',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consommation',
            name='consommation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consommation',
            name='consommation_totale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consommation',
            name='kilometrage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consommation',
            name='mois',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consommation',
            name='type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contratachat',
            name='chassis',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contratachat',
            name='marque',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contratachat',
            name='modele',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contratachat',
            name='moteur',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contratachat',
            name='prix',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contratachat',
            name='vendeur',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contratlocation',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contratlocation',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contratlocation',
            name='marque',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contratlocation',
            name='modele',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contratlocation',
            name='prix',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='activite',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='carrosserie',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='charge_utile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='consommation',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='constructeur',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='cylidree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='date_pmc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='energie',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='engin',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='entretien',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='genre',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='kilometrage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='nombre_debout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='nombre_essieux',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='nombre_places',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='num_serie',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='poids_vide',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='ptac_ptra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='puissance_fiscale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='type_commercial',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='type_constructeur',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
