# Generated by Django 4.0.4 on 2022-04-29 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('reference', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('article', models.CharField(max_length=25)),
                ('codecasier', models.CharField(max_length=25)),
                ('dateachat', models.DateField()),
                ('quantite', models.IntegerField()),
                ('unite', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('numero', models.CharField(max_length=25)),
                ('tiers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_tiers', to='tiers.tiers')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('article', models.CharField(max_length=25)),
                ('nombre', models.IntegerField()),
                ('description', models.TextField(max_length=255)),
                ('statut', models.CharField(max_length=25)),
                ('demandeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_demande_achat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
