# Generated by Django 4.0.4 on 2022-04-29 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flotte', '0001_initial'),
        ('tiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheTrajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('marchandise', models.CharField(max_length=25)),
                ('trajet', models.CharField(max_length=25)),
                ('unite', models.CharField(max_length=25)),
                ('type_prestation', models.CharField(max_length=25)),
                ('categorie', models.CharField(max_length=25)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('prix', models.IntegerField()),
                ('prix_retour', models.IntegerField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiche_trajet_tiers', to='tiers.tiers')),
            ],
        ),
        migrations.CreateModel(
            name='DossierVoyage',
            fields=[
                ('code', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('ref_aller', models.IntegerField()),
                ('date_creation', models.DateField()),
                ('remorque', models.CharField(max_length=25)),
                ('voyage', models.CharField(max_length=25)),
                ('date_chargement', models.DateField()),
                ('date_dechargement', models.DateField()),
                ('montant_ht', models.IntegerField()),
                ('etat', models.CharField(max_length=25)),
                ('chauffeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_voyage_personnel', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_voyage_client', to='tiers.tiers')),
                ('vehicule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_voyage_vehicule', to='flotte.vehicule')),
            ],
        ),
    ]
